global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using A55.Subdivisions.Aws.Tests.TestUtils;
global using Bogus.Extensions;
global using FakeItEasy;
global using FakeItEasy.AutoFakeIt;
global using FluentAssertions;
global using NUnit.Framework;
global using IMessage = A55.Subdivisions.Aws.Models.IMessage<string>;
